basePath: /
definitions:
  controllers.AuthUser:
    properties:
      email:
        example: user@mail.ru
        type: string
      password:
        example: "123456789"
        type: string
    required:
    - email
    - password
    type: object
  controllers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  controllers.RecoverUserPassword:
    properties:
      email:
        example: user@mail.ru
        type: string
    required:
    - email
    type: object
  controllers.SignUpUser:
    properties:
      email:
        example: user@mail.ru
        type: string
      password:
        example: "123456789"
        type: string
      passwordrepeat:
        example: "123456789"
        type: string
    required:
    - email
    - password
    - passwordrepeat
    type: object
  controllers.UserPassword:
    properties:
      password:
        example: "123456789"
        type: string
      passwordrepeat:
        example: "123456789"
        type: string
    required:
    - password
    - passwordrepeat
    type: object
  controllers.UserProfile:
    properties:
      birthDate:
        example: 01.01.2000
        type: string
      mobilePhone:
        example: +7(705)1112233
        type: string
      username:
        example: Tilda
        minLength: 2
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API Server for Ozinwe
  title: Ozinwe API
  version: "1.0"
paths:
  /all:
    get:
      consumes:
      - application/json
      operationId: get-all-movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetAllMovies
      tags:
      - movie-controller
  /anime:
    get:
      consumes:
      - application/json
      operationId: get-anime
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetAnime
      tags:
      - main-page-controller
  /changepassword:
    post:
      consumes:
      - application/json
      operationId: change-password
      parameters:
      - description: changePassword
        in: body
        name: changePassword
        required: true
        schema:
          $ref: '#/definitions/controllers.UserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: ChangePassword
      tags:
      - user-controller
  /editprofile:
    get:
      consumes:
      - application/json
      operationId: edit-user-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: EditUserProfile
      tags:
      - user-controller
  /home:
    get:
      consumes:
      - application/json
      operationId: home
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Home
      tags:
      - main-page-controller
  /horor:
    get:
      consumes:
      - application/json
      operationId: get-horor
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetHoror
      tags:
      - main-page-controller
  /login:
    post:
      consumes:
      - application/json
      operationId: log-in
      parameters:
      - description: loginRequest
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/controllers.AuthUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Login
      tags:
      - auth-controller
  /logout:
    post:
      consumes:
      - application/json
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - auth-controller
  /movie/{id}:
    get:
      consumes:
      - application/json
      operationId: get-movie-by-id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetMovieByID
      tags:
      - movie-controller
  /movie/{id}/series/{seasonid}/{seriesid}:
    get:
      consumes:
      - application/json
      operationId: get-movie-series-by-id
      parameters:
      - description: movieid
        in: path
        name: id
        required: true
        type: integer
      - description: seasonid
        in: path
        name: seasonid
        required: true
        type: integer
      - description: seriesid
        in: path
        name: seriesid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetMovieSeriesByID
      tags:
      - movie-controller
  /newprojects:
    get:
      consumes:
      - application/json
      operationId: get-new-projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetNewprojects
      tags:
      - main-page-controller
  /passwordrecover:
    post:
      consumes:
      - application/json
      operationId: password-recover
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/controllers.RecoverUserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: PasswordRecover
      tags:
      - password-controller
  /resetpassword:
    post:
      consumes:
      - application/json
      operationId: password-reset
      parameters:
      - description: token received in the URL
        in: query
        name: token
        required: true
        type: string
      - description: resetPassword
        in: body
        name: resetPassword
        required: true
        schema:
          $ref: '#/definitions/controllers.UserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: ResetPassword
      tags:
      - password-controller
  /search:
    get:
      consumes:
      - application/json
      operationId: search
      parameters:
      - description: search param received in the URL
        in: query
        name: search
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Search
      tags:
      - search-controller
  /signup:
    post:
      consumes:
      - application/json
      operationId: create-account
      parameters:
      - description: signupRequest
        in: body
        name: signupRequest
        required: true
        schema:
          $ref: '#/definitions/controllers.SignUpUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: SignUp
      tags:
      - auth-controller
  /telehikaya:
    get:
      consumes:
      - application/json
      operationId: get-telehikaya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetTelehikaya
      tags:
      - main-page-controller
  /trends:
    get:
      consumes:
      - application/json
      operationId: get-trends
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetTrends
      tags:
      - main-page-controller
  /updateprofile:
    put:
      consumes:
      - application/json
      operationId: update-user-profile
      parameters:
      - description: updateUserProfile
        in: body
        name: updateUserProfile
        required: true
        schema:
          $ref: '#/definitions/controllers.UserProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: UpdateUserProfile
      tags:
      - user-controller
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
