basePath: /
definitions:
  controllers.User:
    properties:
      email:
        example: user@mail.ru
        type: string
      password:
        example: "123456789"
        type: string
      passwordrepeat:
        example: "123456789"
        type: string
    required:
    - email
    - password
    - passwordrepeat
    type: object
  controllers.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API Server for Ozinwe
  title: Ozinwe API
  version: "1.0"
paths:
  /signup:
    post:
      consumes:
      - application/json
      operationId: create-account
      parameters:
      - description: signupRequest
        in: body
        name: signupRequest
        required: true
        schema:
          $ref: '#/definitions/controllers.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: SignUp
      tags:
      - auth-controller
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
